bugfixing .logs and .gzs

diff --git a/src/xtf b/src/xtf
--- a/src/xtf
+++ b/src/xtf
@@ -61,22 +61,20 @@ while [ "$#" -gt 0 ]; do
         shift
         ;;
 
-    *.log | *.log.gz)
-        while [ "$#" -gt 0 ]; do
-            case "$1" in
-            *.gz)
-                LOG_INPUT="${LOG_INPUT}\n$(gzip -d -c "$1")"
-                ;;
-            *)
-                LOG_INPUT="${LOG_INPUT}$(cat "$1")"
-                ;;
-            esac
-            shift
-        done
+    *.gz)
+        LOG_INPUT="${LOG_INPUT}\n$(gzip -d -c "$1")"
+        shift
         ;;
 
     *)
-        USER="$1"
+        if [ -z "$USER" ]; then
+            USER="$1"
+        else
+            if ! LOG_INPUT="${LOG_INPUT}\n$(cat "$1")"; then
+                echo "" && echo "Error reading file $1" >&2
+                exit 4
+            fi
+        fi
         shift
         ;;
     esac
@@ -168,11 +166,13 @@ case "$COMMAND" in
 list | "")
     echo "$LIST"
     ;;
+
 list-currency)
     echo "$LIST" | awk -F ";" "{
         print \$3
     }" | sort | uniq
     ;;
+
 status)
     echo "$LIST" | awk -F ";" "{
         currency = \$3
@@ -187,6 +187,7 @@ status)
             }
     }"
     ;;
+
 profit)
     echo "$LIST" | awk -F ";" -v xtf_profit="${XTF_PROFIT:-20}" "{
         currency = \$3
