Working version with checking logs format, but it's very slow

diff --git a/src/xtf b/src/xtf
--- a/src/xtf
+++ b/src/xtf
@@ -1,7 +1,8 @@
 #!/bin/sh
 
 export POSIXLY_CORRECT=yes
-export LC_NUMERIC=en_US.UTF-8
+export LC_ALL="C"
+set -e
 
 print_help() {
     echo "Usage: xtf [-h|--help] [FILTER] [COMMAND] USER LOG [LOG2 [...]"
@@ -22,6 +23,7 @@ check_datetime_format() {
         return 0
     else
         echo "Invalid DATETIME format." >&2
+        echo ""
         exit 1
     fi
 }
@@ -104,17 +106,95 @@ parse_arguments() {
         echo "No user specified." >&2
         exit 3
     fi
+
+    if [ -z "$LOG_INPUT" ]; then
+        echo "No file loaded from input." >&2
+        exit 4
+    fi
+
+}
+
+check_logs_format() {
+    if ! printf "%s\n" "$LOG_INPUT" | while IFS=';' read -r user datetime currency value; do
+        if [ -z "$user" ]; then
+            echo "No user specified in logs." >&2
+            exit 1
+        fi
+
+        if [ -z "$datetime" ]; then
+            echo "No datetime specified in logs." >&2
+            exit 2
+        else
+            check_datetime_format "$datetime"
+        fi
+
+        if ! echo "$currency" | grep -qE "^[A-Z]{3}$"; then
+            echo "Invalid currency format in logs." >&2
+            exit 3
+        fi
+
+        if ! echo "$value" | grep -Eq "^(-?[0-9]+(\.[0-9]+))$"; then
+            echo "Invalid price format in logs." >&2
+            exit 4
+        fi
+
+    done; then
+        exit 5
+    fi
 }
 
 filter_input() {
-    # filter input to only include the lines with the specified user
-    # then filter based on the input filters
-    LIST=$(echo "$LOG_INPUT" | awk -F ";" -v user="$USER" "{
+    # LIST=$(echo "$LOG_INPUT" | awk -F ";" -v inputuser="$USER" "{
+    #     error = 0
+    #     user = \$1
+    #     datetime = \$2
+    #     currency = \$3
+    #     price = \$4
+
+    #     if (length(user) == 0)
+    #     {
+    #         error = 1
+    #         exit error
+    #     }
+
+    #     if (length(datetime) == 0 || datetime !~ /^[0-9]{4}-[0-1][0-9]-[0-3][0-9] [0-2][0-9]:[0-5][0-9]:[0-5][0-9]$/)
+    #     {
+    #         error = 2
+    #         exit error
+    #     }
+
+    #     if (length(currency) == 0 || currency !~ /^[A-Z]{3}$/)
+    #     {
+    #         error = 3
+    #         exit error
+    #     }
+
+    #     if (length(price) == 0 || price !~ /^([+-]?[0-9]+(\.[0-9]+))$/)
+    #     {
+    #         error = 4
+    #         exit error
+    #     }
+
+    #     if (\$1 == inputuser)
+    #     {
+    #         printf \"%s\n\", \$0
+    #     }
+    # } END {
+    #     # TODO FIGURE THIS SHIT OUT
+    #     if (error != 0)
+    #     {
+    #         print error > \"/dev/stderr\"
+    #     }
+    # }")
+
+    LIST=$(
+        echo "$LOG_INPUT" | awk -F ";" -v user="$USER" "{
         if (\$1 == user)
         {
             printf \"%s\n\", \$0
         }
-    }")
+    }"
+    )
 
     if [ -n "$AFTER_TIME" ]; then
         LIST=$(echo "$LIST" | awk -F ";" -v after_time="$AFTER_TIME" "{
@@ -210,6 +290,7 @@ show_output() {
 
 main() {
     parse_arguments "$@"
+    check_logs_format
     filter_input
     show_output
     exit 0
